### ISSUE TITLE
Support UnsafeValues#getDataVersion

### ISSUE THREAD

**Issue by LynxPlay101** [seeseemelk/MockBukkit#18]
While working with MockBukkit, I was working on deserializing ItemStacks using the BukkitObjectInputStream. 

While the ItemFactory is mocked fine, this method is for some reason called when deserializing ItemStacks. 

While the value seems to be rather random on the spigot implementation, it simply needs to be a constant value. E.g: In 1.14 this value is always 1952. 
We could simple return a 1 in this case (it cannot be 0 as that is considered unset), as it really does not matter what value it uses.

**Comment by MiniDigger** [comment]
I disagree that it doesn't matter which version it is, since some plugins rely on the data version or other things.
Ideally there would be a setter for that value.

**Comment by LynxPlay101** [comment]
I cannot think of a use-case in which the data version should matter. The interface is already deprecated, hence direct calls to it are not encouraged. The PR is unfortunately already merged, so you will have to open your own PR

**Comment by seeseemelk** [comment]
While creating MockBukkit I've seen Bukkit make some weird method calls. Calls that have to be implemented, but whose values or actions don't matter at all. If these methods are only used internally, then whatever return value works is good enough for me. Also, since it's part of the UnsafeValues class there is no telling what changes might happen to it in the future, and keeping that up to date could potentially create major headaches in the future.
If it wasn't Unsafe I would try to replicate Bukkit behaviour exactly, but unsafe is per definition unsafe. Using those methods within a plugin guarantees nothing.

**Comment by LynxPlay101** [comment]
Is this update going to be deployed to the maven repo ?

**Comment by seeseemelk** [comment]
It has been deployed to maven central
